# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Into The Void' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  #pod 'Firebase/Core'
  #pod 'Firebase/Auth'
  #pod 'Firebase/Database'
  #pod 'Firebase/Storage'


  # Pods for Into The Void

end
